[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 6
padding.y = 6
decorations = "None"
opacity = 0.90

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 9

[colors]
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'