PKGS=(
    hyprland
    hyprpaper
    uwsm
    openssh
    wofi
    waybar
    noto-fonts
    noto-fonts-emoji
    power-profiles-daemon
    networkmanager
    bluez
    bluez-utils
    sof-firmware
    pipewire
    pipewire-audio
    wireplumber
    pipewire-pulse
    pipewire-alsa
    pipewire-jack
    pipewire-bluetooth
    bash-completion
    git
    fzf
    ripgrep
    bat
    less
    eza
    zoxide
    plocate
    btop
    tldr
    fd
    fastfetch
    alacritty
    zellij
    ttf-cascadia-mono-nerd
    mise
    neovim
    docker
    github-cli
    starship
    # AUR Packages
    google-chrome
    visual-studio-code-bin
    lazydocker
    lazygit
)
